### PR TITLE
fix: update tree-sitter mappings

### LINKED ISSUE #91: [Question]: How to find highlight group after `_get_hl_from_capture` was removed?
Does this repo require the upstream builtin treesitter support to finish their implementation before highlight groups can be correctly displayed like they were before?

I see a similar issue was opened [#89](https://github.com/nvim-treesitter/playground/issues/89) that only showed that there was an error that occurred due to what I am asking about here.

For example, before this was removed from this repository, this is what was shown:
I can go into my configuration and specify that I want to change `luaTSFunction` and the color of the item that I am currently hovering above will change to that color.

```
# Treesitter
* @variable -> luaTSVariable -> TSVariable
* @field -> luaTSField -> TSField
* @function -> luaTSFunction -> TSFunction

# Syntax
* luaFunc -> Identifier
* luaFuncSig -> luaFuncSig
* luaFuncId -> Function
* luaFuncName -> Function
```

After this function was removed, this is what is shown:
The highlight groups are still the same name as above, but now `luafunction` provides no meaning to me as someone who wants to create or alter a theme.

```
# Treesitter
* @variable -> luavariable -> variable
* @field -> luafield -> field
* @function -> luafunction -> function
# Syntax
* luaFunc -> luaFunc
* luaFuncSig -> luaFuncSig
* luaFuncId -> Function
* luaFuncName -> Function
```

Also, this might not be the exact place to ask this question, but are filetype specific highlight groups being erased? That is, `luaTSField` vs `TSField`. (I hope that they aren't.)

### PR DESCRIPTION
**Pull request by theHamsta**
Fixes #91

### CODE REVIEW

File: lua/nvim-treesitter-playground/utils.lua [hunk 1]
```diff
@@ -65,12 +65,7 @@ function M.get_hl_groups_at_position(bufnr, row, col)
       if hl and ts_utils.is_in_node_range(node, row, col) then
         local c = query._query.captures[capture] -- name of the capture in the query
         if c ~= nil then
-          local general_hl, is_vim_hl = c, false
-          local local_hl = not is_vim_hl and (tree:lang() .. general_hl)
-          table.insert(
-            matches,
-            { capture = c, specific = local_hl, general = general_hl, priority = metadata.priority }
-          )
+          table.insert(matches, { capture = c, priority = metadata.priority })
```
Comment (theHamsta) [inline lua/nvim-treesitter-playground/utils.lua:68]: previous revision of the PR had `@function -> @function` not sure whether that is clearer. Or should we display `@function.lua`

Comment (clason) [reply lua/nvim-treesitter-playground/utils.lua:68]: If you want to be explicit, the full chain is (for a fictive example)
```
@function.special.lua -> @function.special -> @function -> TSFunction -> Function
```
(with the `TSFunction` being a compatibility shim we haven't decided what to do with after 0.8). Users can break this chain at any point by `hi link @function.special.lua Foo`, which ideally should be reflected.

**Review by clason — APPROVED** [review]

**Comment by clason** [comment]
That can be done later, though (possibly in core); this is already a good fix.
